import Vue from 'vue';
import VMdijs from 'vue-mdijs';
import {
  mdiFolderOutline,
  mdiPlus,
  mdiMagnify,
  mdiChevronDown,
  mdiStarOutline,
  mdiStar,
  mdiDeleteOutline,
  mdiArchiveOutline,
  mdiClose,
  mdiLabelOutline,
  mdiFile,
  mdiMoonWaningCrescent,
  mdiDotsHorizontal,
  mdiPencil,
  mdiMenu,
  mdiAccountCircleOutline,
  mdiAccountCogOutline,
  mdiLogoutVariant,
  mdiCodeTags,
  mdiViewDashboard,
  mdiAccountBox,
  mdiCubeScan,
  mdiDelete,
} from '@mdi/js';

VMdijs.add({
  mdiFolderOutline,
  mdiPlus,
  mdiMagnify,
  mdiChevronDown,
  mdiStarOutline,
  mdiStar,
  mdiDeleteOutline,
  mdiArchiveOutline,
  mdiClose,
  mdiLabelOutline,
  mdiFile,
  mdiMoonWaningCrescent,
  mdiDotsHorizontal,
  mdiPencil,
  mdiMenu,
  mdiAccountCircleOutline,
  mdiAccountCogOutline,
  mdiLogoutVariant,
  mdiCodeTags,
  mdiViewDashboard,
  mdiAccountBox,
  mdiCubeScan,
  mdiDelete,
});

Vue.use(VMdijs);
